dist: xenial
language: node_js
node_js:
  - 12
addons:
  apt:
    sources:
      - google-chrome
        key_url: 'https://dl.google.com/linux/linux_signing_key.pub'
    packages:
      - google-chrome-stable
      - coreutils
before_install:
  - npm i -g yarn@1
install: 
 - yarn
script:
  - yarn bootstrap:packages
  - yarn ci
