dist: xenial
language: node_js
node_js:
  - 10
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - coreutils
before_install:
  - npm i -g yarn@1
install: 
 - yarn
 - lerna bootstrap
before_script: webdriver-manager update
script:
  - lerna run build
  - lerna run ci
