language: node_js
node_js:
  - 8
  - 10
cache: node_modules
before_install:
- '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest'
- npm install -g greenkeeper-lockfile
install: cd example && npm install && cd ../src && npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - cd src && npm run build && PACKAGE=`npm pack`
  - cd ../example && npm i -D ../src/$PACKAGE && ng test
