dist: xenial
language: node_js
node_js:
  - 12
addons:
  apt:
    packages:
      - coreutils
  chrome: stable
before_install:
  - npm i -g yarn@1
install: 
 - yarn
script:
  - yarn bootstrap:packages
  - yarn ci
