dist: xenial
language: node_js
node_js:
  - 10
addons:
  apt:
    packages:
      - coreutils
  chrome: stable
before_install:
  - npm i -g yarn@1
  - chmod +x -R ./scripts
install: ./scripts/install_all.sh
script:
  - sh -x ./scripts/ci_all.sh
